const test=require('node:test');const assert=require('node:assert/strict');
const {evaluateOption,pareto,configure,MODULES}=require('../habitat/config-engine/model.js');
const {jurisdictions,productionProfiles}=require('../habitat/config-engine/catalog.js');const modules=require('../habitat/config-engine/modules.js');
test('currency changes landed economics',()=>{const o={origin:'X',currency:'EUR',materialCost:100};assert.equal(evaluateOption(o,{fx:{EUR:10}}).metrics.cost,1000);});
test('automation reduces modeled labor cost',()=>{const b={origin:'NO',currency:'NOK',laborHours:100,laborRate:100};assert.ok(evaluateOption({...b,automation:.8},{fx:{NOK:1}}).metrics.cost<evaluateOption({...b,automation:0},{fx:{NOK:1}}).metrics.cost);});
test('local assembly responds to jurisdiction labor',()=>{const o={origin:'NO',currency:'NOK',localAssemblyHours:10};assert.equal(evaluateOption(o,{fx:{NOK:1},localLaborRate:700}).metrics.cost,7000);});
test('pareto removes option worse on every axis',()=>{const a={metrics:{cost:1,leadTime:1,risk:1,co2:1,capital:1}},b={metrics:{cost:2,leadTime:2,risk:2,co2:2,capital:2}};assert.deepEqual(pareto([a,b]),[a]);});
test('catalog covers complete subsystem set',()=>assert.deepEqual(modules.map(x=>x.id),MODULES));
test('country configuration evaluates all modules',()=>{for(const c of ['NO','PT']){const r=configure({jurisdiction:jurisdictions[c],productionProfiles,modules});assert.equal(r.evaluated.length,10);assert.ok(r.evaluated.every(m=>m.options.length&&m.pareto.length));}});
test('country labor changes otherwise identical local assembly economics',()=>{const o={origin:'NO',currency:'NOK',localAssemblyHours:10};const no=evaluateOption(o,{fx:{NOK:1},localLaborRate:jurisdictions.NO.localLaborRate});const pt=evaluateOption(o,{fx:{NOK:1},localLaborRate:jurisdictions.PT.localLaborRate});assert.notEqual(no.metrics.cost,pt.metrics.cost);});
